spring:
  session:
    store-type: none
http:
  mappers:
    jsonPrettyPrint: true
mysql:
  mapperLocations: classpath*:/mybatis/mapper/**/*.xml
  configLocation: classpath:/mybatis/mybatis-config.xml
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8011
downloadCenter:
  downloadUrl: www.config.com
