server:
  port: 8762

spring:
  application:
      name: eureka-server

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

eureka:
  instance:
    prefer-ip-address: true
    hostname: peer1
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    # 自我保护
    enable-self-preservation: false
    # 主动检查服务时间
    eviction-interval-timer-in-ms: 5000
    # 服务过期时间，超过这个时间剔除服务
    lease-expiration-duration-in-seconds: 15
    # 服务刷新时间 主动心跳
    lease-renewal-interval-in-seconds: 5
    # 禁用readOnlyCacheMap
    useReadOnlyResponseCache: false







